/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import java.util.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author e-ari
 */
public class PaysHistorial extends javax.swing.JPanel {

    /**
     * Creates new form PaysHistorial
     */
    private DefaultTableModel model;
    public PaysHistorial() {
        initComponents();
        this.model = (DefaultTableModel)this.tablePays.getModel();
        this.fillTable("", "");
    }
    
    private void fillTable(String last, String init){
        
        Server server  = Server.getInstance();
        String query="";
        if(last!=""){
            
            query="SELECT idpay,service,datepay,tipepay,amount FROM pay WHERE datepay>=\'"+init+"\' AND datepay<=\'"+last+"\' ORDER BY datepay DESC;";
            System.out.println(query);
        
        }else{
            query="SELECT idpay,service,datepay,tipepay,amount FROM pay ORDER BY datepay DESC;";
        
        }
        
        
        ResultSet result = server.getResult(query);
        
        try{
            while(result.next()){
                String[] row = new String[5];
                
                
                row[0] = result.getString(1);
                row[1] = result.getString(2);
                row[2] = result.getString(3);
                row[3] = result.getString(4)=="1"? "deposito":"contado";//operador ternario
                row[4] = result.getString(5);
                this.model.addRow(row);
            }
        }catch(SQLException ex){
        }
    
    }
    private String convertDate(Date date){
        String dateResult="";
        int year= date.getYear()+1900;
        int month = date.getMonth()+1;
        int day = date.getDate();
        System.out.println("AÑO: "+year);
        System.out.println("MES: "+month);
        System.out.println("DIA: "+day);
        dateResult=year+"-"+month+"-"+day;
        return dateResult;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        initDate = new rojeru_san.componentes.RSDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePays = new javax.swing.JTable();
        lastDate = new rojeru_san.componentes.RSDateChooser();
        calculateButton = new javax.swing.JButton();
        calculateButton1 = new javax.swing.JButton();

        tablePays.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Service", "Date", "Type", "amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePays);

        calculateButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        calculateButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        calculateButton1.setText("Generate PDF");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(initDate, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(lastDate, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(calculateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(calculateButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(initDate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastDate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculateButton)
                    .addComponent(calculateButton1))
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        // TODO add your handling code here:
        if(this.initDate.getDatoFecha()==null || this.lastDate.getDatoFecha()==null  ){
            System.out.println("No hay fecha seleccionada");
           
        }else{
            long diff = this.lastDate.getDatoFecha().getTime()-this.initDate.getDatoFecha().getTime();
            if(diff<=0){
                
                System.out.println("Rango Incorrecto");
            }else{
                
                this.model.setRowCount(0);
                this.fillTable( this.convertDate(this.lastDate.getDatoFecha()),this.convertDate(this.initDate.getDatoFecha()));
            }
        }
        
        
    }//GEN-LAST:event_calculateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateButton;
    private javax.swing.JButton calculateButton1;
    private rojeru_san.componentes.RSDateChooser initDate;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.componentes.RSDateChooser lastDate;
    private javax.swing.JTable tablePays;
    // End of variables declaration//GEN-END:variables
}
