package principal;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author losa
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.addPanels();
        setLocationRelativeTo(null);
        
    }
    public void addPanels(){
        UserSuscribe us =new UserSuscribe();
        panelprincipal.add("Suscriptions",us);
        PaysRegister p = new PaysRegister();
        ShowServices ss = new ShowServices();
        panelprincipal.add("Services",ss);
        
       
        
        RegisterUser userregister=new RegisterUser();
        panelprincipal.add("User Register",userregister);
        
        RegisterService services=new RegisterService();
        panelprincipal.add("Service Register",services);
        
        UserControl uscontrol=new UserControl();
        panelprincipal.add("User control",uscontrol);
        
<<<<<<< HEAD:ServiciosStreaming/src/principal/Principal.java
        PaysHistorial phistorial = new PaysHistorial();
        panelprincipal.add("Historial",phistorial);
        
=======
        
>>>>>>> 1fbf0b65cd432e862888f706e51096e77588fdfe:ServiciosStreaming/src/Principal.java
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelprincipal = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane panelprincipal;
    // End of variables declaration//GEN-END:variables

    private static class PaysRegister {

        public PaysRegister() {
        }
    }
}
