

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author losa
 */
public class ConfirmForm extends javax.swing.JFrame {
    private int idcostumer;
    private int idservice;

    /**
     * Creates new form ConfirmForm
     */
    public ConfirmForm() {
        initComponents();
    }
    public void setData(int idcostumer, int idservice){
        this.idcostumer=idcostumer;
        this.idservice=idservice;
        dataLogin(idservice);
        setLocationRelativeTo(null);
    }
    public void dataLogin(int id){
        Server server=Server.getInstance();
        String sql="SELECT email, contrasenia FROM Servicio WHERE id = "+id;
        ResultSet rq=server.getResult(sql);
        try{
            if(rq.next()){
                String email= rq.getString(1);
                String pass= rq.getString(2);
                infoField.setText("Correo:"+email+"   contraseña:"+pass);
                
            }
        
        }catch(SQLException ex){
            
        }
    }
    
    private void SuccesfulSuscribe(){
        Server server=Server.getInstance();
        String user= userField.getText();
        String sql="SELECT * FROM Suscriptores WHERE user =\'"+user+"\'";
        
        ResultSet result=server.getResult(sql);
        
        
        
        try{
            if(result.next()){
                //Debe cambiar de usuario
                alertLabel.setText("usuario existente");
            }else{
                
                if(calendar.getDatoFecha()==null){
                    JOptionPane.showMessageDialog(this, "Select Date","Error",JOptionPane.ERROR_MESSAGE);
                }else{
                    
                    Date fecha = (Date) calendar.getDatoFecha();
            
                    int day=fecha.getDate();
                    int month=fecha.getMonth()+1;
                    int anio=fecha.getYear()+1900;
                    String date=anio+"-"+month+"-"+day;
                    
                    sql="INSERT INTO Suscriptores(user,idservicios,idCliente,fecha,estado) "
                        +"VALUES (\'"+user+"\',"+ this.idservice+","+this.idcostumer+",\'"+date+"\',\'activo\')";
                    
                    result=server.getResult(sql);
                    
                    if(result.next()){
                        sql="UPDATE Servicio SET activos = activos +"+1+" WHERE id = "+this.idservice;
                        server.getResult(sql);
                        dispose();
                    }
                    
                    
            
            //System.out.println(day: "+day+" month: "+month+" anio: "+anio);
                }
                
                
            }
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
        
    }
    
    /*
    if(calendar.getDatoFecha()==null){
            JOptionPane.showMessageDialog(this, "Select Date","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            String dateFormat= "dd MMMM yyyy";
            Date fecha = (Date) calendar.getDatoFecha();
            SimpleDateFormat format= new SimpleDateFormat(dateFormat);
            System.out.println("fecha: "+format.format(fecha));
            System.out.println("fecha2: "+fecha);
        }
    }       
    */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        userField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        infoField = new javax.swing.JTextField();
        calendar = new rojeru_san.componentes.RSDateChooser();
        alertLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        jButton1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton1.setText("CONFIRM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton2.setText("CANCEL");

        userField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Usuario:");

        infoField.setBackground(new java.awt.Color(204, 51, 0));
        infoField.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        infoField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        calendar.setColorBackground(new java.awt.Color(102, 102, 102));

        alertLabel.setForeground(new java.awt.Color(204, 51, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoField)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(calendar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)
                                .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alertLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alertLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.SuccesfulSuscribe();
        /*if(calendar.getDatoFecha()==null){
            JOptionPane.showMessageDialog(this, "Select Date","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            String dateFormat= "yy MMMM dd";
            Date fecha = (Date) calendar.getDatoFecha();
            
            int day=fecha.getDate();
            int month=fecha.getMonth()+1;
            int anio=fecha.getYear()+1900;
            
            //System.out.println(day: "+day+" month: "+month+" anio: "+anio);
        }*/
    
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertLabel;
    private rojeru_san.componentes.RSDateChooser calendar;
    private javax.swing.JTextField infoField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
}
