
import java.sql.ResultSet;
import java.sql.SQLException;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author losa
 */
public class ShowServices extends javax.swing.JPanel {
    private int rowSelected;
    private int idservice;
    private DefaultTableModel model;
    public ShowServices() {
        initComponents();
        this.rowSelected=0;
        this.idservice=1;
        this.model = (DefaultTableModel)this.tableServices.getModel();
        this.fillTable();
        
    }
    
    private void fillTable(){
        Server server = Server.getInstance();
        
        String sql = "SELECT id, nombre,fechaPago, maxactivos, activos FROM Servicio ORDER BY fechaPago ASC;";
        
        ResultSet result = server.getResult(sql);
        
        try{
            while(result.next()){
                String[] row = new String[5];
                
                row[0] = result.getString(1);
                row[1] = result.getString(2);
                row[2] = result.getString(3);
                row[3] = result.getString(4);
                row[4] = result.getString(5);
                this.model.addRow(row);
                
                
                
            }
        
        }catch(SQLException ex){
        
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableServices = new javax.swing.JTable();
        viewUserButton = new javax.swing.JButton();
        suscribeButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        suscribeButton1 = new javax.swing.JButton();

        tableServices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Tipo de Servicios", "Pago cada", "Max", "Activos"
            }
        ));
        tableServices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableServicesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableServices);

        viewUserButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        viewUserButton.setText("View Users");
        viewUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUserButtonActionPerformed(evt);
            }
        });

        suscribeButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        suscribeButton.setText("Suscribe");

        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        suscribeButton1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        suscribeButton1.setText("Update");
        suscribeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suscribeButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(viewUserButton)
                                .addGap(28, 28, 28)
                                .addComponent(suscribeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(suscribeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 129, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewUserButton)
                    .addComponent(suscribeButton)
                    .addComponent(suscribeButton1))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableServicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableServicesMouseClicked
        this.rowSelected = tableServices.rowAtPoint(evt.getPoint());
        
        
        try{
            
            this.idservice= Integer.parseInt( this.model.getValueAt(this.rowSelected, 0).toString());
            
        }catch(Exception e){
            System.out.println(e.getMessage());     
        }
        
    }//GEN-LAST:event_tableServicesMouseClicked

    private void viewUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUserButtonActionPerformed
        // TODO add your handling code here:
        
        ShowUsers show = new ShowUsers(this.idservice);
        show.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        show.setVisible(true);
    }//GEN-LAST:event_viewUserButtonActionPerformed

    private void suscribeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suscribeButton1ActionPerformed
        // TODO add your handling code here:
        this.model.setRowCount(0);
        this.fillTable();
    }//GEN-LAST:event_suscribeButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton suscribeButton;
    private javax.swing.JButton suscribeButton1;
    private javax.swing.JTable tableServices;
    private javax.swing.JButton viewUserButton;
    // End of variables declaration//GEN-END:variables
}
