
import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author losa
 */
public class ViewSuscriptions extends javax.swing.JFrame {
    private DefaultTableModel model;
    private int rowSelected;
    private int indexService;
    private int indexCustomer;
    private int idservice;
    /**
     * Creates new form ViewSuscriptions
     */
    public ViewSuscriptions() {
        
        initComponents();
        
        ShowServices ss = new ShowServices();
        ss.setPreferredSize(new Dimension(300,400));
        this.getContentPane().add(ss);
        this.add(ss);
        
        this.rowSelected=0;
        this.idservice=1;
        
        nameLabel.setVisible(false);
        suscribeButton.setVisible(false);
        model=(DefaultTableModel)tableServices.getModel();
        llenarTable();
        setLocationRelativeTo(null);
        
    }
    private void llenarTable(){
        Server server=Server.getInstance();
        ResultSet result=server.getResult("SELECT * FROM Servicio;");
        
        try{
            while(result.next()){
                String[] row=new String[4];
                
                row[0]=String.valueOf(result.getInt(1));
                row[1]=result.getString(2);
                row[2]=String.valueOf(result.getInt(7));
                row[3]=String.valueOf(result.getInt(8));
                //System.out.println(result.getInt(1));
                
                
                
                this.model.addRow(row);
                
            }
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
            
        }
    }
    public void addSuscription(int idCustomer){
        System.out.println("index customer: "+idCustomer);
        this.indexCustomer=idCustomer;
        Server server=Server.getInstance();
        
        ResultSet result=server.getResult("SELECT C.nombre1, C.apellido1 FROM Clientes AS C WHERE id = "+idCustomer);
        
        try{
            if(result.next()){
                nameLabel.setText(result.getNString(1)+" "+result.getNString(2));
                nameLabel.setVisible(true);
                suscribeButton.setVisible(true);
            }
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
        
    }
    private void Suscribe(){
        Server server=Server.getInstance();
        String sql="SELECT * FROM Servicio WHERE id ="+this.indexService;
        ResultSet rq = server.getResult(sql);
        try{
            while(rq.next()){
                if(rq.getInt(7)>rq.getInt(8)){
                    System.out.println("Si se puede agregar");
                    ConfirmForm confirm= new ConfirmForm();
                    confirm.setData(this.indexCustomer, this.indexService);
                    confirm.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    dispose();
                    confirm.setVisible(true);
                    
                    
                }else{
                    System.out.println("No hay cupo");
                }
            }
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableServices = new javax.swing.JTable();
        suscribeButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        viewUserButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableServices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Tipo de Servicios", "Max", "Activos"
            }
        ));
        tableServices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableServicesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableServices);

        suscribeButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        suscribeButton.setText("Suscribe");
        suscribeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suscribeButtonActionPerformed(evt);
            }
        });

        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        viewUserButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        viewUserButton.setText("View Users");
        viewUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(viewUserButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(suscribeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(202, 202, 202))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suscribeButton)
                    .addComponent(viewUserButton))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableServicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableServicesMouseClicked
        this.rowSelected = tableServices.rowAtPoint(evt.getPoint());

        try{

            this.idservice= Integer.parseInt( this.model.getValueAt(this.rowSelected, 0).toString());

        }catch(Exception e){
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_tableServicesMouseClicked

    private void viewUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUserButtonActionPerformed
        // TODO add your handling code here:

        ShowUsers show = new ShowUsers(this.idservice);
        show.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        show.setVisible(true);
    }//GEN-LAST:event_viewUserButtonActionPerformed

    private void suscribeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suscribeButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        ConfirmForm cf = new ConfirmForm();
        cf.setData(indexCustomer, idservice);
        cf.dataLogin(idservice);
        cf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        cf.setVisible(true);
    }//GEN-LAST:event_suscribeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton suscribeButton;
    private javax.swing.JTable tableServices;
    private javax.swing.JButton viewUserButton;
    // End of variables declaration//GEN-END:variables
}
